cell.o: cell.cc voronoicell_base.hh common.hh config.hh voronoicell.hh \
 voronoicell_neighbor.hh
common.o: common.cc common.hh config.hh
container.o: container.cc wall_list.hh wall.hh voronoicell.hh \
 voronoicell_base.hh common.hh config.hh voronoicell_neighbor.hh \
 container_base.hh v_base.hh worklist.hh container.hh particle_order.hh \
 c_loop_all.hh c_loop_base.hh radius_mono.hh v_compute.hh \
 particle_record.hh container_poly.hh radius_poly.hh
unitcell.o: unitcell.cc unitcell.hh voronoicell.hh voronoicell_base.hh \
 common.hh config.hh
v_compute.o: v_compute.cc v_compute.hh particle_record.hh config.hh \
 worklist.hh container.hh container_base.hh common.hh wall_list.hh \
 wall.hh voronoicell.hh voronoicell_base.hh voronoicell_neighbor.hh \
 v_base.hh particle_order.hh c_loop_all.hh c_loop_base.hh radius_mono.hh \
 container_poly.hh radius_poly.hh container_periodic.hh \
 container_periodic_base.hh unitcell.hh c_loop_all_periodic.hh \
 container_periodic_poly.hh
c_loops.o: c_loops.cc c_loop_subset.hh c_loop_base.hh config.hh \
 c_loop_subset_mode.hh particle_order.hh
v_base.o: v_base.cc v_base.hh worklist.hh config.hh v_base_wl.cc
wall.o: wall.cc wall_sphere.hh wall.hh voronoicell.hh voronoicell_base.hh \
 common.hh config.hh voronoicell_neighbor.hh wall_plane.hh \
 wall_cylinder.hh wall_cone.hh
pre_container.o: pre_container.cc pre_container_base.hh config.hh \
 pre_container.hh common.hh particle_order.hh container.hh \
 container_base.hh wall_list.hh wall.hh voronoicell.hh \
 voronoicell_base.hh voronoicell_neighbor.hh v_base.hh worklist.hh \
 c_loop_all.hh c_loop_base.hh radius_mono.hh v_compute.hh \
 particle_record.hh pre_container_poly.hh container_poly.hh \
 radius_poly.hh
container_prd.o: container_prd.cc container_periodic_base.hh common.hh \
 config.hh unitcell.hh voronoicell.hh voronoicell_base.hh v_base.hh \
 worklist.hh container_periodic.hh particle_order.hh \
 c_loop_all_periodic.hh c_loop_base.hh radius_mono.hh v_compute.hh \
 particle_record.hh voronoicell_neighbor.hh container_periodic_poly.hh \
 radius_poly.hh
